[
  {
    "Sl No": 1,
    Crop: "Tomato",
    "Pest/Disease": "Early blight",
    "Severity of the problem": "No disease",
    "Proactive/Reactive": "Reactive",
    Duration: 20,
    "Condition (weather)": "Not favourable",
    "Prev Spray Relevance": "Relevant / Irrelevant",
    "Management (technical name)": "No spray",
  },
  {
    Crop: "Tomato",
    "Pest/Disease": "Early blight",
    "Severity of the problem": "No disease",
    "Proactive/Reactive": "Reactive",
    "Condition (weather)": "Favourable",
    "Application Method": "Spray",
    "Management (technical name)": "Mancozeb 75% WP",
    Dose: 3,
    Unit: "g/lit",
    "Trade Name 1": "Indofil M 45",
    Company: "Indofil",
    "Trade Name 2": "Abic",
    Company_1: "Syngenta",
    "Trade Name 3": "Uthane 45",
    Company_2: "UPL",
  },
  {
    Crop: "Tomato",
    "Pest/Disease": "Early blight",
    "Severity of the problem": "No disease",
    "Proactive/Reactive": "Reactive",
    "Condition (weather)": "Favourable",
    "Management (technical name)": "Propineb",
    Dose: 2,
    Unit: "g/lit",
    "Trade Name 1": "Antracol",
    Company: "BAYER",
    "Trade Name 2": "Proximain",
    Company_1: "ADAMA",
  },
  {
    Crop: "Tomato",
    "Pest/Disease": "Early blight",
    "Severity of the problem": "No disease",
    "Proactive/Reactive": "Reactive",
    "Condition (weather)": "Favourable",
    "Management (technical name)": "CHLOROTHALANIL 78.12% WP",
    Dose: 2,
    Unit: "g/lit",
    "Trade Name 1": "Kavach",
    Company: "SYNGENTA",
  },
  {
    Crop: "Tomato",
    "Pest/Disease": "Early blight",
    "Severity of the problem": "Moderate",
    "Proactive/Reactive": "Reactive",
    "Condition (weather)": "Favourable",
    "Prev Spray Relevance": "Relevant",
    "Management (technical name)": "Captan 70 + Hexaconazole 5%",
    Dose: 2,
    Unit: "g/lit",
    "Trade Name 1": "taqat",
    Company: "RALLIS",
    "Trade Name 2": "captcha",
    Company_1: "BEST AGRO LIFE",
    "Trade Name 3": "Faida",
    Company_2: "SWAL",
  },
  {
    Crop: "Tomato",
    "Pest/Disease": "Early blight",
    "Severity of the problem": "Moderate",
    "Proactive/Reactive": "Reactive",
    "Condition (weather)": "Not favourable",
    "Prev Spray Relevance": "Irrelevant",
    "Management (technical name)": "TEBUCONAZOLE 18.3% + AZOXYSTROBIN 11%",
    Dose: 1.5,
    Unit: "ml/lit",
    "Trade Name 1": "Custodia",
    Company: "ADAMA",
  },
  {
    Crop: "Tomato",
    "Pest/Disease": "Early blight",
    "Severity of the problem": "Moderate",
    "Proactive/Reactive": "Reactive",
    "Condition (weather)": "Favourable",
    "Prev Spray Relevance": "Relevant",
    "Management (technical name)": "Captan 60 + Hexaconazole 5%",
    Dose: 2,
    Unit: "g/lit",
    "Trade Name 1": "taqat",
    Company: "RALLIS",
    "Trade Name 2": "captcha",
    Company_1: "BEST AGRO LIFE",
    "Trade Name 3": "Faida",
    Company_2: "SWAL",
    "Management (technical name)_1": "a1",
    Dose_1: 6,
    Unit_1: "ml",
    "Trade Name 1_1": "Y1",
    "Trade Name 2_1": "Y2",
    "Trade Name 3_1": "Y3",
    "Management (technical name)_2": "B1",
    "Trade Name 1_2": "Z1",
    "Trade Name 2_2": "Z2",
    "Trade Name 3_2": "Z3",
  },
  {
    Crop: "Tomato",
    "Pest/Disease": "Early blight",
    "Severity of the problem": "Moderate",
    "Proactive/Reactive": "Reactive",
    "Condition (weather)": "Favourable",
    "Prev Spray Relevance": "Irrelevant",
    "Management (technical name)": "TEBUCONAZOLE 18.3% + AZOXYSTROBIN 11%",
    Dose: 1.5,
    Unit: "ml/lit",
    "Trade Name 1": "Custodia",
    Company: "ADAMA",
  },
  {
    Crop: "Tomato",
    "Pest/Disease": "Early blight",
    "Severity of the problem": "Severe",
    "Proactive/Reactive": "Reactive",
    "Management (technical name)":
      "Azoxystrobin 18.2% w/w + Difenoconazole 11.4%",
    Dose: 1,
    Unit: "ml/lit",
    "Trade Name 1": "Dronex",
    Company: "GSP",
    "Trade Name 2": "Amistar Top",
    Company_1: "SYNGENTA",
  },
  {
    Crop: "Tomato",
    "Pest/Disease": "Early blight",
    "Severity of the problem": "Severe",
    "Proactive/Reactive": "Reactive",
    "Management (technical name)":
      "Picoxystrobin 6.78% + Tricyclazole 20.33 % SC",
    Dose: 2,
    Unit: "ml/lit",
    "Trade Name 1": "Slogan",
    Company: "Nagarjuna chemicals",
    "Trade Name 2": "KRONOS",
    Company_1: "SWAL",
  },
  {
    "Sl No": 2,
    Crop: "Tomato",
    "Pest/Disease": "Late blight",
    "Severity of the problem": "Preventive",
    Duration: 40,
    "Management (technical name)": "Mancozeb 75% WP",
    Dose: 3,
    Unit: "g/lit",
    "Trade Name 1": "Indofil M 45",
    Company: "Indofil",
    "Trade Name 2": "Abic",
    Company_1: "Syngenta",
    "Trade Name 3": "Uthane 45",
    Company_2: "UPL",
  },
  {
    Crop: "Tomato",
    "Pest/Disease": "Late blight",
    "Severity of the problem": "Preventive",
    "Management (technical name)": "Propineb",
    Dose: 2,
    Unit: "g/lit",
    "Trade Name 1": "Antracol",
    Company: "BAYER",
    "Trade Name 2": "Proximain",
    Company_1: "ADAMA",
  },
  {
    Crop: "Tomato",
    "Pest/Disease": "Late blight",
    "Severity of the problem": "Preventive",
    "Management (technical name)": "Chlorothalonil",
    Dose: 2,
    Unit: "g/lit",
    "Trade Name 1": "Kavach",
    Company: "SYNGENTA",
  },
  {
    Crop: "Tomato",
    "Pest/Disease": "Late blight",
    "Severity of the problem": "Moderate",
    "Management (technical name)": "Cymoxanil 8 % + Mancozeb 64 WP",
    Dose: 3,
    Unit: "g/lit",
    "Trade Name 1": "Moximate",
    Company: "INDOFIL",
    "Trade Name 2": "CRIZOL ",
    Company_1: "TROPICAL AGRO ",
    "Trade Name 3": "CURZATE M8 72% WP ",
    Company_2: "CORTEVA ",
  },
  {
    Crop: "Tomato",
    "Pest/Disease": "Late blight",
    "Severity of the problem": "Moderate",
    "Management (technical name)": "FAMOXADONE 16.6% + CYMOXANIL 22.1%SC",
    Dose: 1,
    Unit: "ml/lit",
    "Trade Name 1": "Eqation pro",
    Company: "CORTEVA ",
  },
  {
    Crop: "Tomato",
    "Pest/Disease": "Late blight",
    "Severity of the problem": "Severe",
    "Management (technical name)": "DIEMETHOMORPH 50%WP",
    Dose: 1,
    Unit: "g/lit",
    "Trade Name 1": "Acrobat",
    Company: "BASF",
    "Trade Name 2": "Trica",
    Company_1: "NAGARJUNA AGRO CHEMICALS",
    And: "And",
    "Management (technical name)_1": "Mancozeb 75% WP",
    Dose_1: 3,
    Unit_1: "g/lit",
    "Trade Name 1_1": "Indofil M 45",
    Company_3: "Indofil",
    "Trade Name 2_1": "Abic",
    Company_4: "Syngenta",
    "Trade Name 3_1": "Uthane 45",
    Company_5: "UPL",
  },
  {
    Crop: "Tomato",
    "Pest/Disease": "Late blight",
    "Severity of the problem": "Severe",
    "Management (technical name)": "FAMOXADONE 16.6% + CYMOXANIL 22.1%SC",
    Dose: 2,
    Unit: "ml/lit",
    "Trade Name 1": "Eqation pro",
    Company: "CORTEVA ",
    And: "And",
    "Management (technical name)_1": "Copperoxy chloride",
    Dose_1: 3,
    Unit_1: "g/lit",
    "Trade Name 1_1": "Maincop",
    Company_3: "ADAMA",
    "Trade Name 2_1": "BLITOX 50 WP",
    Company_4: "Rallis",
  },
  {
    Crop: "Tomato",
    "Pest/Disease": "Late blight",
    "Severity of the problem": "Severe",
    "Management (technical name)": "Famaxodone + Cymoxinil",
    Dose: 2,
    Unit: "ml/lit",
    "Trade Name 1": "Eqation pro",
    Company: "CORTEVA ",
    And: "And",
    "Management (technical name)_1": "COPPER HYDROXIDE 46.1% WG",
    Dose_1: 2,
    Unit_1: "g/lit",
    "Trade Name 1_1": "Kocide 3000",
    Company_3: "BHARAT CERTIS",
  },
  {
    Crop: "Tomato",
    "Pest/Disease": "Late blight",
    "Severity of the problem": "Severe",
    "Management (technical name)": "DIEMETHOMORPH 9% + METIRAM 44% WG",
    Dose: 5,
    Unit: "g/lit",
    "Trade Name 1": "ACROBAT COMPLETE",
    Company: "BASF",
  },
  {
    Crop: "Tomato",
    "Pest/Disease": "Late blight",
    "Severity of the problem": "Severe",
    "Management (technical name)":
      "AMETOCTRADIN 27 % + DIMETHOMORPH 20.27 % SC",
    Dose: 2.5,
    Unit: "ml/lit",
    "Trade Name 1": "Zampro",
    Company: "BASF",
  },
  {
    "Sl No": 3,
    Crop: "Tomato",
    "Pest/Disease": "Powdery mildew",
    "Severity of the problem": "Early",
    Duration: 50,
    "Management (technical name)": "Myclobutanil",
    Dose: 0.5,
    Unit: "g/lit",
    "Trade Name 1": "Cygnet",
    Company: "BIOSTADT",
    "Trade Name 2": "Boon",
    Company_1: "INDOFIL",
    "Trade Name 3": "Matrix",
    Company_2: "TROPICAL AGRO",
  },
  {
    Crop: "Tomato",
    "Pest/Disease": "Powdery mildew",
    "Severity of the problem": "Moderate",
    "Management (technical name)": "TEBUCONAZOLE 18.3% + AZOXYSTROBIN 11%",
    Dose: 1.5,
    Unit: "ml/lit",
    "Trade Name 1": "Custodia",
    Company: "ADAMA",
  },
  {
    Crop: "Tomato",
    "Pest/Disease": "Powdery mildew",
    "Severity of the problem": "Moderate",
    "Management (technical name)": "Captan 70 + Hexaconazole 5%",
    Dose: 2,
    Unit: "g/lit",
    "Trade Name 1": "taqat",
    Company: "TATA RALLIS",
    "Trade Name 2": "captcha",
    Company_1: "BEST AGRO LIFE",
    "Trade Name 3": "Faida",
    Company_2: "SWAL",
  },
  {
    Crop: "Tomato",
    "Pest/Disease": "Powdery mildew",
    "Severity of the problem": "Moderate",
    "Management (technical name)": "KRESOXIM-METHYL 44.3% w/w",
    Dose: 0.6,
    Unit: "ml/lit",
    "Trade Name 1": "Tata ayaan",
    Company: "TATA RALLIS",
  },
  {
    Crop: "Tomato",
    "Pest/Disease": "Powdery mildew",
    "Severity of the problem": "Moderate",
    "Management (technical name)": "Bupirimate 26.7% w/w EC",
    Dose: 2,
    Unit: "ml/lit",
    "Trade Name 1": "Nimrod",
    Company: "ADAMA",
  },
  {
    Crop: "Tomato",
    "Pest/Disease": "Powdery mildew",
    "Severity of the problem": "Severe",
    "Management (technical name)":
      "FLUOPYRAM 17.7%+ TEBUCONAZOLE17.7% W/W SC (400 SC)",
    Dose: 1,
    Unit: "ml/lit",
    "Trade Name 1": "Luna experiance ",
    Company: "BAYER",
    "Trade Name 2": "KIVALO",
    Company_1: "FMC",
  },
  {
    Crop: "Tomato",
    "Pest/Disease": "Powdery mildew",
    "Severity of the problem": "Severe",
    "Management (technical name)":
      "Azoxystrobin 18.2% w/w + Difenoconazole 11.4%",
    Dose: 1,
    Unit: "ml/lit",
    "Trade Name 1": "Dronex",
    Company: "GSP",
    "Trade Name 2": "Amistar Top",
    Company_1: "SYNGENTA",
  },
  {
    Crop: "Tomato",
    "Pest/Disease": "Powdery mildew",
    "Severity of the problem": "Severe",
    "Management (technical name)": "KRESOXIM-METHYL 40% + HEXACONAZOLE 8% WG",
    Dose: 1,
    Unit: "g/lit",
    "Trade Name 1": "Tata ayaan",
    Company: "TATA RALLIS",
  },
  {
    "Sl No": 4,
    Crop: "Tomato",
    "Pest/Disease": "Bacterial spots / specs / canker",
    "Severity of the problem": "Low/Medium",
    Duration: 70,
    "Management (technical name)": "COPPER HYDROXIDE 46.1% WG",
    Dose: 2,
    Unit: "g/lit",
    "Trade Name 1": "Kocide 3000",
    Company: "BHARAT CERTIS",
    And: "And",
    "Management (technical name)_1": "Streptocyclin",
    Dose_1: 0.5,
    Unit_1: "g/lit",
    "Trade Name 1_1": "Bactrinash",
    Company_3: "INDOFIL",
  },
  {
    Crop: "Tomato",
    "Pest/Disease": "Bacterial spots / specs / canker",
    "Severity of the problem": "Low/Medium",
    "Management (technical name)": "Copperoxy chloride",
    Dose: 3,
    Unit: "g/lit",
    "Trade Name 1": "Maincop",
    Company: "ADAMA",
    "Trade Name 2": "BLITOX 50 WP",
    Company_1: "Rallis",
    And: "And",
    "Management (technical name)_1": "Streptocyclin",
    Dose_1: 0.5,
    Unit_1: "g/lit",
    "Trade Name 1_1": "Bactrinash",
    Company_3: "INDOFIL",
  },
  {
    Crop: "Tomato",
    "Pest/Disease": "Bacterial spots / specs / canker",
    "Severity of the problem": "High",
    "Management (technical name)": "COPPER HYDROXIDE 46.1% WG",
    Dose: 2,
    Unit: "g/lit",
    "Trade Name 1": "Kocide 3000",
    Company: "BHARAT CERTIS",
    And: "And",
    "Management (technical name)_1": "Streptocyclin",
    Dose_1: 0.5,
    Unit_1: "g/lit",
    "Trade Name 1_1": "Bactrinash",
    Company_3: "INDOFIL",
  },
  {
    Crop: "Tomato",
    "Pest/Disease": "Bacterial spots / specs / canker",
    "Severity of the problem": "High",
    "Management (technical name)": "COPPER HYDROXIDE 46.1% WG",
    Dose: 2,
    Unit: "g/lit",
    "Trade Name 1": "Kocide 3000",
    Company: "BHARAT CERTIS",
  },
  {
    "Sl No": 5,
    Crop: "Tomato",
    "Pest/Disease": "Septoria leaf spot",
    "Severity of the problem": "Preventive",
    "Management (technical name)": "Mancozeb 75% WP",
    Dose: 3,
    Unit: "g/lit",
    "Trade Name 1": "Indofil M 45",
    Company: "Indofil",
    "Trade Name 2": "Abic",
    Company_1: "Syngenta",
    "Trade Name 3": "Uthane 45",
    Company_2: "UPL",
  },
  {
    Crop: "Tomato",
    "Pest/Disease": "Septoria leaf spot",
    "Severity of the problem": "Preventive",
    "Management (technical name)": "Propineb",
    Dose: 2,
    Unit: "g/lit",
    "Trade Name 1": "Antracol",
    Company: "BAYER",
    "Trade Name 2": "Proximain",
    Company_1: "ADAMA",
  },
  {
    Crop: "Tomato",
    "Pest/Disease": "Septoria leaf spot",
    "Severity of the problem": "Preventive",
    "Management (technical name)": "CHLOROTHALANIL 78.12% WP",
    Dose: 2,
    Unit: "g/lit",
    "Trade Name 1": "Kavach",
    Company: "SYNGENTA",
  },
  {
    Crop: "Tomato",
    "Pest/Disease": "Septoria leaf spot",
    "Severity of the problem": "Moderate",
    "Management (technical name)": "Captan 70 + Hexaconazole 5%",
    Dose: 2,
    Unit: "g/lit",
    "Trade Name 1": "taqat",
    Company: "TATA RALLIS",
    "Trade Name 2": "captcha",
    Company_1: "BEST AGRO LIFE",
    "Trade Name 3": "Faida",
    Company_2: "SWAL",
  },
  {
    Crop: "Tomato",
    "Pest/Disease": "Septoria leaf spot",
    "Severity of the problem": "Moderate",
    "Management (technical name)": "TEBUCONAZOLE 18.3% + AZOXYSTROBIN 11%",
    Dose: 1.5,
    Unit: "ml/lit",
    "Trade Name 1": "Custodia",
    Company: "ADAMA",
  },
  {
    Crop: "Tomato",
    "Pest/Disease": "Septoria leaf spot",
    "Severity of the problem": "Severe",
    "Management (technical name)":
      "Azoxystrobin 18.2% w/w + Difenoconazole 11.4%",
    Dose: 1,
    Unit: "ml/lit",
    "Trade Name 1": "Dronex",
    Company: "GSP",
    "Trade Name 2": "Amistar Top",
    Company_1: "SYNGENTA",
  },
  {
    Crop: "Tomato",
    "Pest/Disease": "Septoria leaf spot",
    "Severity of the problem": "Severe",
    "Management (technical name)": "Pyraclostrobin + Tricyclazole ",
    Dose: 2,
    Unit: "ml/lit",
  },
  {
    "Sl No": 6,
    Crop: "Tomato",
    "Pest/Disease": "Fuarium wilt and Verticellium (Drench)",
    "Severity of the problem": "All conditions",
    "Management (technical name)": "Copper oxy chloride",
    Dose: 3,
    Unit: "g/lit",
    "Trade Name 1": "Maincop",
    Company: "ADAMA",
    "Trade Name 2": "BLITOX 50 WP",
    Company_1: "Rallis",
  },
  {
    Crop: "Tomato",
    "Pest/Disease": "Fuarium wilt and Verticellium (Drench)",
    "Severity of the problem": "All conditions",
    "Management (technical name)": "Propiconazole",
    Dose: 2,
    Unit: "ml/lit",
    "Trade Name 1": "Tilt",
    Company: "CRYSTAL",
    "Trade Name 2": "Bumper",
    Company_1: "ADAMA",
    "Trade Name 3": "Zerox",
    Company_2: "DHANUKA",
  },
  {
    Crop: "Tomato",
    "Pest/Disease": "Bacterial wilt (Drench)",
    "Severity of the problem": "All conditions",
    "Management (technical name)": "Copper oxy chloride",
    Dose: 3,
    Unit: "g/lit",
    "Trade Name 1": "Maincop",
    Company: "ADAMA",
    "Trade Name 2": "BLITOX 50 WP",
    Company_1: "Rallis",
    And: "And",
    "Management (technical name)_1": "Streptocyclin",
    Dose_1: 0.5,
    Unit_1: "g/lit",
    "Trade Name 1_1": "Bactrinash",
    Company_3: "INDOFIL",
  },
  {
    Crop: "Tomato",
    "Pest/Disease": "Bacterial wilt (Drench)",
    "Severity of the problem": "All conditions",
    "Management (technical name)": "Nano silver hydrogen peroxide",
    Dose: 3,
    Unit: "ml/lit",
  },
  { Crop: "Tomato", "Pest/Disease": "Blossom end rot" },
  { Crop: "Tomato", "Pest/Disease": "Blossom end rot" },
  {
    "Sl No": 7,
    Crop: "Tomato",
    "Pest/Disease": "Damping off / collar rot",
    "Severity of the problem": "All conditions",
    "Management (technical name)": "METALAXYL 4% + MANCOZEB 64%",
    Dose: 2,
    Unit: "g/lit",
    "Trade Name 1": "Ridomil gold",
    Company: "SYNGENTA",
  },
  {
    Crop: "Tomato",
    "Pest/Disease": "Damping off / collar rot",
    "Severity of the problem": "All conditions",
    "Management (technical name)": "FOSETYL-AL",
    Dose: 2,
    Unit: "g/lit",
    "Trade Name 1": "ALIETTE",
    Company: "BAYER",
  },
  {
    Crop: "Tomato",
    "Pest/Disease": "Damping off / collar rot",
    "Severity of the problem": "All conditions",
    "Management (technical name)": "Copper oxy chloride",
    Dose: 3,
    Unit: "g/lit",
    "Trade Name 1": "Maincop",
    Company: "ADAMA",
    "Trade Name 2": "BLITOX 50 WP",
    Company_1: "Rallis",
  },
  { "Severity of the problem": "Diagnose" },
  {
    "Severity of the problem": "Disease",
    "Proactive/Reactive": "Early Blight",
  },
  {
    "Severity of the problem": "Severity of the problem",
    "Proactive/Reactive": "Proactive/Reactive",
    Duration: "Duration",
    "Condition (weather)": "Condition (weather)",
    "Prev Spray Relevance": "Prev Spray Relevance",
    "Soil Type??": "Soil Type??",
  },
  { "Severity of the problem": "Prescribe" },
  { "Sl No": " " },
  { "Management (technical name)": " Hexaconazole 1", Unit: "taqat" },
  { Unit: "captcha" },
  { Unit: "Faida" },
  { "Management (technical name)": "Hexaconazole 2", Unit: "taqat" },
  { Unit: "captcha" },
  { Unit: "Faida" },
  { Dose: "AND" },
  { "Management (technical name)": "C", Unit: "C1" },
  { Unit: "C2" },
  { Unit: "C3" },
  { "Management (technical name)": "D", Unit: "C1" },
  { Unit: "C2" },
  { Unit: "C3" },
  { Dose: "AND" },
  { "Management (technical name)": "E", Unit: "D1" },
  { Unit: "D2" },
  { Unit: "D3" },
  { "Management (technical name)": "F", Unit: "D1" },
  { Unit: "D2" },
  { Unit: "D3" },
];
